### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by woutersj** [mgubi/tm_jupyter#4]
The below are some of the improvements that I'd like to implement in the near future.

- [x] flush images as inline TeXmacs images
- [ ] fix autocomplete with empty string to be replaced (e.g. completion after a dot in Python)
- [ ] add syntax highlighting by getting the language name from the Jupyter kernel
- [ ] Flush verbatim in new utf-8 format
- [ ] add kernel selection for executable folds
- [ ] improve ANSI filters (don't simply remove them)
- [ ] add autocomplete in multiline statements
- [ ] Update output lines, e.g. while doing Pkg.add("DynamicalSystems") we get a lot of "Fetching ... XX.X%" lines.
- [ ] use loci to render display_data with a display_id and parse update_display_data messages
- [ ] add completeness detection (to switch to Multiline input)

**Comment by fbob** [comment]
Do you think the architecture of Texmacs and/or this plugin could allow the development of widgets, like in "classic" jupyter-notebooks ?

**Comment by mgubi** [comment]
Note: the discussion on the interactivity of the plugins is being carried on also on the forum: http://forum.texmacs.cn/t/julia-programming-language/115/12

**Comment by fbob** [comment]
Ok, noted
Thanks
